#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

{{ if .Values.javadoc.deploy }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: javadoc-{{ .Values.javadoc.branch }}
  namespace: {{ .Values.namespace }}
    
spec:
  ingressClassName: public-iks-k8s-nginx
  tls:
  - hosts:
    - development.galasa.dev
    secretName: devgalasa-tls-secret
  rules:
  - host: development.galasa.dev
    http:
      paths:
      - backend:
          service:
            name: javadoc-{{ .Values.javadoc.branch }}
            port:
              number: 80
        path: /{{ .Values.javadoc.branch }}/maven-repo/javadoc
        pathType: Prefix
{{ end }}