#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#


namespace: galasa-development

managers:
  deploy: false
  branch: main
  imageName: harbor.galasa.dev/galasadev/galasa-managers
  imageTag: main
extensions:
  deploy: false
  branch: main
  imageName: harbor.galasa.dev/galasadev/galasa-extensions
  imageTag: main
codecov:
  deploy: false
  branch: main
  imageName: harbor.galasa.dev/galasadev/galasa-codecoverage
  imageTag: main      
framework:
  deploy: false
  branch: main
  imageName: harbor.galasa.dev/galasadev/galasa-framework
  imageTag: main 
obr:
  deploy: false
  branch: main
  imageName: harbor.galasa.dev/galasadev/galasa-obr
  imageTag: main
maven:
  deploy: false
  branch: main
  imageName: harbor.galasa.dev/galasadev/galasa-maven
  imageTag: main
gradle:
  deploy: false
  branch: main
  imageName: harbor.galasa.dev/galasadev/galasa-gradle
  imageTag: main
isolated:
  deploy: false
  branch: main
  imageName: icr.io/galasadev/galasa-isolated-zip
  imageTag: main
javadoc:
  deploy: false
  branch: main
  imageName: harbor.galasa.dev/galasadev/galasa-javadoc-maven-repo
  imageTag: main
javadocsite:
  deploy: false
  branch: main
  imageName: harbor.galasa.dev/galasadev/galasa-javadoc-site
  imageTag: main  
restApiDocSite:
  deploy: false
  branch: main
  imageName: harbor.galasa.dev/galasadev/galasa-restapidoc-site
  imageTag: main 
mvp:
  deploy: false
  branch: main
  imageName: icr.io/galasadev/galasa-mvp-zip
  imageTag: main
wrapping:
  deploy: false
  branch: main
  imageName: harbor.galasa.dev/galasadev/galasa-wrapping
  imageTag: main