#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

{{ if .Values.obr.deploy }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obr-{{ .Values.obr.branch }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
    
spec:
  tls:
  - hosts:
    - development.galasa.dev
    secretName: devgalasa-tls-secret
  rules:
  - host: development.galasa.dev
    http:
      paths:
      - backend:
          service:
            name: obr-{{ .Values.obr.branch }}
            port:
              number: 80
        path: /{{ .Values.obr.branch }}/maven-repo/obr
        pathType: Prefix
{{ end }}