#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#


namespace: galasa-development
     
obr:
  deploy: false
  branch: main
  imageName: ghcr.io/galasa-dev/obr-maven-artefacts
  imageTag: main
isolated:
  deploy: false
  branch: main
  imageName: ghcr.io/galasa-dev/galasa-isolated-zip
  imageTag: main
javadoc:
  deploy: false
  branch: main
  imageName: ghcr.io/galasa-dev/javadoc-maven-artefacts
  imageTag: main
mvp:
  deploy: false
  branch: main
  imageName: ghcr.io/galasa-dev/galasa-mvp-zip
  imageTag: main