#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

{{ if .Values.mvp.deploy }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mvp-{{ .Values.mvp.branch }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.org/client-max-body-size: "20m"
    
spec:
  ingressClassName: public-iks-k8s-nginx
  tls:
  - hosts:
    - development.galasa.dev
    secretName: devgalasa-tls-secret
  rules:
  - host: development.galasa.dev
    http:
      paths:
      - backend:
          service:
            name: mvp-{{ .Values.mvp.branch }}
            port:
              number: 80
        path: /{{ .Values.mvp.branch }}/maven-repo/mvp
        pathType: Prefix
{{ end }}