#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

# A list of DNS names to issue a certificate for
# For example, to issue a certificate for 'myservice.galasa.dev', the value would look like:
#
# dnsNames:
#   - myservice.galasa.dev
#
dnsNames:
  # - development.galasa.dev
  - development.galasa-kube1-d2e8765deb38dddd0aa1b649462cf87f-0000.eu-gb.containers.appdomain.cloud

# The name of the ingress class that you are using for your exposed Ingress resources.
# Different cloud providers may offer their own ingress classes. For example, IBM Cloud
# offers 'public-iks-k8s-nginx' and 'private-iks-k8s-nginx' classes.
ingressClassName: public-iks-k8s-nginx

# Determines whether the Issuer resource should use a production URL to issue certificates.
# When `useIssuerProductionUrl` is false, the ACME staging URL will be used (https://acme-staging-v02.api.letsencrypt.org/directory).
# When `useIssuerProductionUrl` is true, the ACME production URL will be used (https://acme-v02.api.letsencrypt.org/directory).
# This value should only be set to true once you have made sure that certificates can be issued successfully using the staging URL.
useIssuerProductionUrl: true

# The email that should receive messages from Let's Encrypt about expiring certificates
# and any issues associated with your account.
#
# Note: There is no mechanism to load an email from a secret, so one has been set on installation.
# Run "kubectl describe issuer devgalasa-tls-letsencrypt-prod" to get the email that has been set.
email: ""
