#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cli-{{ .Values.branch }}
  namespace: {{ .Values.namespace }}
    
spec:
  ingressClassName: public-iks-k8s-nginx
  tls:
  - hosts:
    - development.galasa.dev
    secretName: devgalasa-tls-secret
  rules:
  - host: development.galasa.dev
    http:
      paths:
      - backend:
          service:
            name: cli-{{ .Values.branch }}
            port:
              number: 80
        path: /{{ .Values.branch }}/binary/cli
        pathType: Prefix