#
# Copyright contributors to the Galasa project 
# 
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapi-base
  namespace: galasa-prod
data:
  apibase.js: |+
    var galasaBootstrap = 'http://galasa-galasa-prod.cicsk8s.hursley.ibm.com/bootstrap' 